### ISSUE TITLE
Full simulation request

### ISSUE THREAD

**Issue by KhaledMousaCpp** [titoirfan/soca_octomap#2]
May you please share the steps of doing coverage planning for each area in the map, octomap settings so that no empty spaces accurse in the place of the robot, SLAM algorithm used to generate the general map. as in this provided map_building.gif
![map_building](https://user-images.githubusercontent.com/100929458/173779913-de72eb9a-f555-40b7-ae7f-3ffe0d60b26b.gif)

Please help me in this meter, as it is the main requirement in my Final year project
My contact details: email: khaledmousa999@hotmail.com / WhatsApp number:+97466746909

**Comment by titoirfan** [comment]
Hi, sorry for the late reply

The coverage planning is done by using the spanning tree coverage planning strategy. We basically discretize each room into a grid of equally sized cells (which can be viewed as a graph), then we build its spanning tree of the grid. The robot will simply follow the spanning tree. For more details, I would recommend reading the Planning Algorithm textbook by Steven M. LaValle.

I didn't use any SLAM algorithm for the robot navigation. I built a map of the environment first using Google's Cartographer, then I ran augmented monte carlo localization (AMCL) to localize the robot.

However, the occupancy grid map shown in the gif is NOT the grid map used by the robot for navigation purposes. It is a map for visualization purposes only, as it should align with the simulated octomap. This visualization map is generated from the 3D model of the environment, I used the code from [this repository](https://github.com/marinaKollmitz/gazebo_ros_2Dmap_plugin) to do it.

As for the octomap settings, I'm afraid that I can't help much as I have forgotten the details of this project. But I think the empty space below the robot can be solved by using finer resolution, and also configuring the simulated 3D lidar parameters (field of view, height, horizontal and vertical number of rays, etc).

**Comment by KhaledMousaCpp** [comment]
> Hi, sorry for the late reply
> 
> The coverage planning is done by using the spanning tree coverage planning strategy. We basically discretize each room into a grid of equally sized cells (which can be viewed as a graph), then we build its spanning tree of the grid. The robot will simply follow the spanning tree. For more details, I would recommend reading the Planning Algorithm textbook by Steven M. LaValle.
> 
> I didn't use any SLAM algorithm for the robot navigation. I built a map of the environment first using Google's Cartographer, then I ran augmented monte carlo localization (AMCL) to localize the robot.
> 
> However, the occupancy grid map shown in the gif is NOT the grid map used by the robot for navigation purposes. It is a map for visualization purposes only, as it should align with the simulated octomap. This visualization map is generated from the 3D model of the environment, I used the code from [this repository](https://github.com/marinaKollmitz/gazebo_ros_2Dmap_plugin) to do it.
> 
> As for the octomap settings, I'm afraid that I can't help much as I have forgotten the details of this project. But I think the empty space below the robot can be solved by using finer resolution, and also configuring the simulated 3D lidar parameters (field of view, height, horizontal and vertical number of rays, etc).

Thanks for your useful information, do you recommend  any repository for **coverage planning strategy** or can you please shear any package that include this strategy so I can know more about the implementation

**Comment by titoirfan** [comment]
@KhaledMousaCpp I implemented it myself back then, however the code quality isn't the best and it was still kind of clunky. I have never tried these myself, but I think I will recommend these repositories instead: https://github.com/nobleo/full_coverage_path_planner and https://github.com/ethz-asl/polygon_coverage_planning
